import { Button, VerticalBox, GroupBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    VerticalLayout {
        alignment: space-between;
        padding: 30px;

        VerticalLayout {
            spacing: 30px;

            VerticalLayout {
                spacing: 10px;

                Text {
                    text: "Weight";
                }

                LineEdit {
                    horizontal-alignment: center;
                    font-size: 16px;
                    input-type: decimal;
                }
            }

            VerticalLayout {
                spacing: 10px;

                Text {
                    text: "Body fat";
                }

                LineEdit {
                    horizontal-alignment: center;
                    font-size: 16px;
                    input-type: decimal;
                }
            }

            VerticalLayout {
                spacing: 10px;
                Text {
                    text: "Muscle mass";
                }

                LineEdit {
                    horizontal-alignment: center;
                    font-size: 16px;
                    input-type: decimal;
                }
            }
        }

        Button {
            text: "submit";
            height: 60px;
        }
    }
}
