import { Button, VerticalBox, GroupBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback submit(string, string, string);

    VerticalLayout {
        alignment: space-between;
        padding: 30px;

        VerticalLayout {
            spacing: 30px;

            VerticalLayout {
                spacing: 10px;

                Text {
                    text: "Weight";
                }

                weight_input := LineEdit {
                    horizontal-alignment: center;
                    font-size: 16px;
                    input-type: decimal;
                }
            }

            VerticalLayout {
                spacing: 10px;

                Text {
                    text: "Body fat";
                }

                body_fat_input := LineEdit {
                    horizontal-alignment: center;
                    font-size: 16px;
                    input-type: decimal;
                }
            }

            VerticalLayout {
                spacing: 10px;
                Text {
                    text: "Muscle mass";
                }

                muscle_mass_input := LineEdit {
                    horizontal-alignment: center;
                    font-size: 16px;
                    input-type: decimal;
                }
            }
        }

        Button {
            text: "submit";
            height: 60px;
            clicked => {
                submit(weight_input.text,body_fat_input.text,muscle_mass_input.text);
            }
        }
    }
}
